/**
 * Generate src/registry.generated.ts from the JSON registries in data/.
 * The JSON files are the source of truth; the generated module is what
 * ships (no JSON at runtime). Regenerating is a deliberate act: the registry
 * `kv` golden vectors pin every name.
 *
 *   bun scripts/generate-registry.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "data");
/**
 * Registry files left out of the bundle: the community file holds one entry,
 * `200000 testWorkflowEntry`, the Research repo's workflow test row, which no
 * formatter should print. Remove it from this list once the file carries a
 * real assignment.
 */
const SKIP = new Set(["100000_community_registry.json"]);
const files = readdirSync(dataDir)
  .filter((f) => f.endsWith(".json") && !SKIP.has(f))
  .sort((a, b) => Number(a.split("_")[0]) - Number(b.split("_")[0]));
const rows: [number, string][] = [];
const sources = [];
for (const f of files) {
  const doc = JSON.parse(readFileSync(join(dataDir, f), "utf8"));
  sources.push(
    `${f} (${doc.entries.length} entries${doc.ontology?.name ? `, ${doc.ontology.name}` : ""})`,
  );
  for (const e of doc.entries) rows.push([e.codepoint, e.name]);
}
const body = rows.map(([cp, name]) => `  [${cp}, ${JSON.stringify(name)}],`).join("\n");
const out = `/**
 * GENERATED by scripts/generate-registry.ts from data/*.json - do not edit.
 *
 * The bundled registries in load order (later rows override earlier ones
 * with the same codepoint when the global store is built):
${sources.map((s) => ` *   ${s}`).join("\n")}
 * Skipped: ${[...SKIP].join(", ")} (see the generator).
 */

/**
 * \`[codepoint, name]\` rows of the bundled registries, in load order. The
 * array is frozen; the store copies the values out, so the rows stay plain
 * tuples.
 */
export const BUNDLED_REGISTRY: readonly (readonly [number, string])[] = /*#__PURE__*/ Object.freeze([
${body}
]);
`;
writeFileSync(join(root, "src/registry.generated.ts"), out);
console.log(`wrote src/registry.generated.ts: ${rows.length} rows from ${files.length} files`);
