import { Cbor, CborCodec, CborTagged, Tag, ToCbor } from "@blockchaincommons/dcbor";
import { Digest, DigestProvider } from "@blockchaincommons/components";
//#region src/known-value.d.ts
/** What a known value can be built from. */
type KnownValueInput = number | bigint;
declare class KnownValue implements ToCbor, CborTagged, DigestProvider {
  private readonly _value;
  private readonly _assignedName;
  /**
   * @param value - The codepoint (an unsigned 64-bit integer)
   * @param assignedName - The name the registry gives it, if any
   */
  constructor(value: KnownValueInput, assignedName?: string);
  static from(value: KnownValueInput, assignedName?: string): KnownValue;
  /** The codepoint, as a `number` when it is a safe integer and a `bigint` otherwise. */
  get value(): number | bigint;
  /** The codepoint as a `bigint`. */
  get valueBigInt(): bigint;
  /** The registry name, if one was assigned. */
  get assignedName(): string | undefined;
  /** The assigned name, or the decimal codepoint when there is none. */
  get name(): string;
  /** Two known values are equal when their codepoints are, whatever their names. */
  equals(other: KnownValue): boolean;
  toString(): string;
  /** SHA-256 of the tagged CBOR. */
  digest(): Digest;
  /** Tagged-CBOR codec; `decode` also accepts the untagged form. */
  static get codec(): CborCodec<KnownValue>;
  cborTags(): Tag[];
  /** The bare unsigned integer. */
  untaggedCbor(): Cbor;
  /** `#6.40000(value)`. */
  toCbor(): Cbor;
  /** Decode tagged (`#6.40000(n)`) or untagged (`n`) CBOR. */
  static fromCbor(cborValue: Cbor): KnownValue;
}
//#endregion
//#region src/known-values-store.d.ts
declare class KnownValuesStore implements Iterable<KnownValue> {
  private _byValue;
  private _byName;
  constructor(knownValues?: Iterable<KnownValue>);
  /**
   * Add or replace a value. A later registration of the same codepoint
   * replaces the earlier one and retires its name.
   */
  register(knownValue: KnownValue): void;
  /** The registered value with this codepoint, if any. */
  byValue(value: KnownValueInput): KnownValue | undefined;
  /** The registered value with this assigned name, if any. */
  byName(assignedName: string): KnownValue | undefined;
  /** The name this store assigns to the value's codepoint, if any. */
  assignedNameOf(knownValue: KnownValue): string | undefined;
  /** The store's name for the codepoint, else the value's own name. */
  nameOf(knownValue: KnownValue): string;
  get size(): number;
  /** Registered values, in registration order. */
  values(): IterableIterator<KnownValue>;
  [Symbol.iterator](): Iterator<KnownValue>;
  clone(): KnownValuesStore;
}
//#endregion
//#region src/registry.d.ts
/** The process-wide registry, built on first call. */
declare function getGlobalKnownValuesStore(): KnownValuesStore;
/** Run `action` with the global registry. */
declare function withKnownValues<T>(action: (store: KnownValuesStore) => T): T;
/**
 * The registered value for a codepoint, or a bare `KnownValue` when the
 * store (the global one by default) does not know it.
 */
declare function resolveKnownValue(value: number | bigint, store?: KnownValuesStore): KnownValue;
//#endregion
//#region src/registry.generated.d.ts
/**
 * GENERATED by scripts/generate-registry.mjs from data/*.json - do not edit.
 *
 * The bundled registries in load order (later rows override earlier ones
 * with the same codepoint when the global store is built):
 *   0_blockchain_commons_registry.json (103 entries, blockchain_commons)
 *   1000_community_registry.json (0 entries, community_registry)
 *   2000_rdf_registry.json (21 entries, rdf)
 *   2050_rdfs_registry.json (15 entries, rdfs)
 *   2100_owl2_registry.json (75 entries, owl2)
 *   2200_dce_registry.json (15 entries, dce)
 *   2300_dct_registry.json (89 entries, dct)
 *   2500_foaf_registry.json (75 entries, foaf)
 *   2700_skos_registry.json (32 entries, skos)
 *   2800_solid_registry.json (33 entries, solid)
 *   2900_vc_registry.json (28 entries, vc)
 *   3000_gs1_registry.json (609 entries, gs1)
 *   10000_schema_registry.json (2450 entries, schema)
 *   100000_community_registry.json (1 entries, community_registry)
 */
/** `[codepoint, name]` rows of the bundled registries, in load order. */
declare const BUNDLED_REGISTRY: readonly (readonly [number, string])[];
//#endregion
//#region src/constants.d.ts
/** Codepoints of the registry constants, for `case` labels and comparisons. */
declare const KNOWN_VALUE_CODEPOINTS: {
  readonly UNIT: 0;
  readonly IS_A: 1;
  readonly ID: 2;
  readonly SIGNED: 3;
  readonly NOTE: 4;
  readonly HAS_RECIPIENT: 5;
  readonly SSKR_SHARE: 6;
  readonly CONTROLLER: 7;
  readonly KEY: 8;
  readonly DEREFERENCE_VIA: 9;
  readonly ENTITY: 10;
  readonly NAME: 11;
  readonly LANGUAGE: 12;
  readonly ISSUER: 13;
  readonly HOLDER: 14;
  readonly SALT: 15;
  readonly DATE: 16;
  readonly UNKNOWN_VALUE: 17;
  readonly VERSION_VALUE: 18;
  readonly HAS_SECRET: 19;
  readonly DIFF_EDITS: 20;
  readonly VALID_FROM: 21;
  readonly VALID_UNTIL: 22;
  readonly POSITION: 23;
  readonly NICKNAME: 24;
  readonly VALUE: 25;
  readonly ATTESTATION: 26;
  readonly VERIFIABLE_AT: 27;
  readonly ATTACHMENT: 50;
  readonly VENDOR: 51;
  readonly CONFORMS_TO: 52;
  readonly ALLOW: 60;
  readonly DENY: 61;
  readonly ENDPOINT: 62;
  readonly DELEGATE: 63;
  readonly PROVENANCE: 64;
  readonly PRIVATE_KEY: 65;
  readonly SERVICE: 66;
  readonly CAPABILITY: 67;
  readonly PROVENANCE_GENERATOR: 68;
  readonly PRIVILEGE_ALL: 70;
  readonly PRIVILEGE_AUTH: 71;
  readonly PRIVILEGE_SIGN: 72;
  readonly PRIVILEGE_ENCRYPT: 73;
  readonly PRIVILEGE_ELIDE: 74;
  readonly PRIVILEGE_ISSUE: 75;
  readonly PRIVILEGE_ACCESS: 76;
  readonly PRIVILEGE_DELEGATE: 80;
  readonly PRIVILEGE_VERIFY: 81;
  readonly PRIVILEGE_UPDATE: 82;
  readonly PRIVILEGE_TRANSFER: 83;
  readonly PRIVILEGE_ELECT: 84;
  readonly PRIVILEGE_BURN: 85;
  readonly PRIVILEGE_REVOKE: 86;
  readonly BODY: 100;
  readonly RESULT: 101;
  readonly ERROR: 102;
  readonly OK_VALUE: 103;
  readonly PROCESSING_VALUE: 104;
  readonly SENDER: 105;
  readonly SENDER_CONTINUATION: 106;
  readonly RECIPIENT_CONTINUATION: 107;
  readonly CONTENT: 108;
  readonly SEED_TYPE: 200;
  readonly PRIVATE_KEY_TYPE: 201;
  readonly PUBLIC_KEY_TYPE: 202;
  readonly MASTER_KEY_TYPE: 203;
  readonly ASSET: 300;
  readonly BITCOIN_VALUE: 301;
  readonly ETHEREUM_VALUE: 302;
  readonly TEZOS_VALUE: 303;
  readonly NETWORK: 400;
  readonly MAIN_NET_VALUE: 401;
  readonly TEST_NET_VALUE: 402;
  readonly BIP32_KEY_TYPE: 500;
  readonly CHAIN_CODE: 501;
  readonly DERIVATION_PATH_TYPE: 502;
  readonly PARENT_PATH: 503;
  readonly CHILDREN_PATH: 504;
  readonly PARENT_FINGERPRINT: 505;
  readonly PSBT_TYPE: 506;
  readonly OUTPUT_DESCRIPTOR_TYPE: 507;
  readonly OUTPUT_DESCRIPTOR: 508;
  readonly GRAPH: 600;
  readonly SOURCE_TARGET_GRAPH: 601;
  readonly PARENT_CHILD_GRAPH: 602;
  readonly DIGRAPH: 603;
  readonly ACYCLIC_GRAPH: 604;
  readonly MULTIGRAPH: 605;
  readonly PSEUDOGRAPH: 606;
  readonly GRAPH_FRAGMENT: 607;
  readonly DAG: 608;
  readonly TREE: 609;
  readonly FOREST: 610;
  readonly COMPOUND_GRAPH: 611;
  readonly HYPERGRAPH: 612;
  readonly DIHYPERGRAPH: 613;
  readonly NODE: 700;
  readonly EDGE: 701;
  readonly SOURCE: 702;
  readonly TARGET: 703;
  readonly PARENT: 704;
  readonly CHILD: 705;
  readonly SELF: 706;
};
declare const UNIT: KnownValue;
declare const IS_A: KnownValue;
declare const ID: KnownValue;
declare const SIGNED: KnownValue;
declare const NOTE: KnownValue;
declare const HAS_RECIPIENT: KnownValue;
declare const SSKR_SHARE: KnownValue;
declare const CONTROLLER: KnownValue;
declare const KEY: KnownValue;
declare const DEREFERENCE_VIA: KnownValue;
declare const ENTITY: KnownValue;
declare const NAME: KnownValue;
declare const LANGUAGE: KnownValue;
declare const ISSUER: KnownValue;
declare const HOLDER: KnownValue;
declare const SALT: KnownValue;
declare const DATE: KnownValue;
declare const UNKNOWN_VALUE: KnownValue;
declare const VERSION_VALUE: KnownValue;
declare const HAS_SECRET: KnownValue;
declare const DIFF_EDITS: KnownValue;
declare const VALID_FROM: KnownValue;
declare const VALID_UNTIL: KnownValue;
declare const POSITION: KnownValue;
declare const NICKNAME: KnownValue;
declare const VALUE: KnownValue;
declare const ATTESTATION: KnownValue;
declare const VERIFIABLE_AT: KnownValue;
declare const ATTACHMENT: KnownValue;
declare const VENDOR: KnownValue;
declare const CONFORMS_TO: KnownValue;
declare const ALLOW: KnownValue;
declare const DENY: KnownValue;
declare const ENDPOINT: KnownValue;
declare const DELEGATE: KnownValue;
declare const PROVENANCE: KnownValue;
declare const PRIVATE_KEY: KnownValue;
declare const SERVICE: KnownValue;
declare const CAPABILITY: KnownValue;
declare const PROVENANCE_GENERATOR: KnownValue;
declare const PRIVILEGE_ALL: KnownValue;
declare const PRIVILEGE_AUTH: KnownValue;
declare const PRIVILEGE_SIGN: KnownValue;
declare const PRIVILEGE_ENCRYPT: KnownValue;
declare const PRIVILEGE_ELIDE: KnownValue;
declare const PRIVILEGE_ISSUE: KnownValue;
declare const PRIVILEGE_ACCESS: KnownValue;
declare const PRIVILEGE_DELEGATE: KnownValue;
declare const PRIVILEGE_VERIFY: KnownValue;
declare const PRIVILEGE_UPDATE: KnownValue;
declare const PRIVILEGE_TRANSFER: KnownValue;
declare const PRIVILEGE_ELECT: KnownValue;
declare const PRIVILEGE_BURN: KnownValue;
declare const PRIVILEGE_REVOKE: KnownValue;
declare const BODY: KnownValue;
declare const RESULT: KnownValue;
declare const ERROR: KnownValue;
declare const OK_VALUE: KnownValue;
declare const PROCESSING_VALUE: KnownValue;
declare const SENDER: KnownValue;
declare const SENDER_CONTINUATION: KnownValue;
declare const RECIPIENT_CONTINUATION: KnownValue;
declare const CONTENT: KnownValue;
declare const SEED_TYPE: KnownValue;
declare const PRIVATE_KEY_TYPE: KnownValue;
declare const PUBLIC_KEY_TYPE: KnownValue;
declare const MASTER_KEY_TYPE: KnownValue;
declare const ASSET: KnownValue;
declare const BITCOIN_VALUE: KnownValue;
declare const ETHEREUM_VALUE: KnownValue;
declare const TEZOS_VALUE: KnownValue;
declare const NETWORK: KnownValue;
declare const MAIN_NET_VALUE: KnownValue;
declare const TEST_NET_VALUE: KnownValue;
declare const BIP32_KEY_TYPE: KnownValue;
declare const CHAIN_CODE: KnownValue;
declare const DERIVATION_PATH_TYPE: KnownValue;
declare const PARENT_PATH: KnownValue;
declare const CHILDREN_PATH: KnownValue;
declare const PARENT_FINGERPRINT: KnownValue;
declare const PSBT_TYPE: KnownValue;
declare const OUTPUT_DESCRIPTOR_TYPE: KnownValue;
declare const OUTPUT_DESCRIPTOR: KnownValue;
declare const GRAPH: KnownValue;
declare const SOURCE_TARGET_GRAPH: KnownValue;
declare const PARENT_CHILD_GRAPH: KnownValue;
declare const DIGRAPH: KnownValue;
declare const ACYCLIC_GRAPH: KnownValue;
declare const MULTIGRAPH: KnownValue;
declare const PSEUDOGRAPH: KnownValue;
declare const GRAPH_FRAGMENT: KnownValue;
declare const DAG: KnownValue;
declare const TREE: KnownValue;
declare const FOREST: KnownValue;
declare const COMPOUND_GRAPH: KnownValue;
declare const HYPERGRAPH: KnownValue;
declare const DIHYPERGRAPH: KnownValue;
declare const NODE: KnownValue;
declare const EDGE: KnownValue;
declare const SOURCE: KnownValue;
declare const TARGET: KnownValue;
declare const PARENT: KnownValue;
declare const CHILD: KnownValue;
declare const SELF: KnownValue;
/** Every registry constant, in codepoint order. */
declare const REGISTRY_CONSTANTS: readonly KnownValue[];
//#endregion
export { ACYCLIC_GRAPH, ALLOW, ASSET, ATTACHMENT, ATTESTATION, BIP32_KEY_TYPE, BITCOIN_VALUE, BODY, BUNDLED_REGISTRY, CAPABILITY, CHAIN_CODE, CHILD, CHILDREN_PATH, COMPOUND_GRAPH, CONFORMS_TO, CONTENT, CONTROLLER, DAG, DATE, DELEGATE, DENY, DEREFERENCE_VIA, DERIVATION_PATH_TYPE, DIFF_EDITS, DIGRAPH, DIHYPERGRAPH, EDGE, ENDPOINT, ENTITY, ERROR, ETHEREUM_VALUE, FOREST, GRAPH, GRAPH_FRAGMENT, HAS_RECIPIENT, HAS_SECRET, HOLDER, HYPERGRAPH, ID, ISSUER, IS_A, KEY, KNOWN_VALUE_CODEPOINTS, KnownValue, type KnownValueInput, KnownValuesStore, LANGUAGE, MAIN_NET_VALUE, MASTER_KEY_TYPE, MULTIGRAPH, NAME, NETWORK, NICKNAME, NODE, NOTE, OK_VALUE, OUTPUT_DESCRIPTOR, OUTPUT_DESCRIPTOR_TYPE, PARENT, PARENT_CHILD_GRAPH, PARENT_FINGERPRINT, PARENT_PATH, POSITION, PRIVATE_KEY, PRIVATE_KEY_TYPE, PRIVILEGE_ACCESS, PRIVILEGE_ALL, PRIVILEGE_AUTH, PRIVILEGE_BURN, PRIVILEGE_DELEGATE, PRIVILEGE_ELECT, PRIVILEGE_ELIDE, PRIVILEGE_ENCRYPT, PRIVILEGE_ISSUE, PRIVILEGE_REVOKE, PRIVILEGE_SIGN, PRIVILEGE_TRANSFER, PRIVILEGE_UPDATE, PRIVILEGE_VERIFY, PROCESSING_VALUE, PROVENANCE, PROVENANCE_GENERATOR, PSBT_TYPE, PSEUDOGRAPH, PUBLIC_KEY_TYPE, RECIPIENT_CONTINUATION, REGISTRY_CONSTANTS, RESULT, SALT, SEED_TYPE, SELF, SENDER, SENDER_CONTINUATION, SERVICE, SIGNED, SOURCE, SOURCE_TARGET_GRAPH, SSKR_SHARE, TARGET, TEST_NET_VALUE, TEZOS_VALUE, TREE, UNIT, UNKNOWN_VALUE, VALID_FROM, VALID_UNTIL, VALUE, VENDOR, VERIFIABLE_AT, VERSION_VALUE, getGlobalKnownValuesStore, resolveKnownValue, withKnownValues };
//# sourceMappingURL=index.d.mts.map